name: dart_jvcl
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

executables:
  jvcl:

environment:
  sdk: '>=2.16.2 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
dependencies: 
  args: ^2.3.1
  darty_json_safe: ^1.0.1
  dio: ^4.0.6
  path: ^1.8.2
  process_run: ^0.12.3+2
  version: ^3.0.2
